# frontend/nginx.conf

server {
  listen 80;
  server_name localhost;

  # Racine du serveur web, où se trouvent nos fichiers React
  root /usr/share/nginx/html;
  index index.html;

  location / {
    # Essaye de servir le fichier demandé directement.
    # S'il n'existe pas, essaye de servir un dossier.
    # Si ça ne fonctionne toujours pas, renvoie vers /index.html.
    # C'est la ligne magique pour les SPA.
    try_files $uri $uri/ /index.html;
  }
}