# pytest.ini
[pytest]
pythonpath = .

# ne plus afficher les DeprecationWarning et le warning de peft
filterwarnings =
    ignore::DeprecationWarning
    ignore:Already found a `peft_config` attribute in the model.*:UserWarning

asyncio_mode = auto
addopts = --tb=short -v
