scrape_configs:
  - job_name: "darija_api"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8001"]
    basic_auth:
      username: admin
      password_file: /run/secrets/prometheus_password
