artifact_uri: /projets/darija_app_final/mlflow-artifacts/619281650037722963/debbfffab7724db5b2c43fed36e2fb99/artifacts
deleted_time: 1752961029183
end_time: null
entry_point_name: ''
experiment_id: '619281650037722963'
lifecycle_stage: deleted
run_id: debbfffab7724db5b2c43fed36e2fb99
run_name: upbeat-rat-662
run_uuid: debbfffab7724db5b2c43fed36e2fb99
source_name: ''
source_type: 4
source_version: ''
start_time: 1752959954080
status: 1
tags: []
user_id: farid
