# Fichier : k8s/api.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ia-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ia-api
  template:
    metadata:
      labels:
        app: ia-api
    spec:
      containers:
      - name: ia-api-container
        image: iaapi.azurecr.io/darija-api:latest
        ports:
        - containerPort: 8001
        
        resources:
          requests:
            cpu: "500m"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "8Gi"
        
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          failureThreshold: 30
          periodSeconds: 10
          timeoutSeconds: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
          
        envFrom:
        - secretRef:
            name: api-secrets
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ia-api-service
spec:
  type: LoadBalancer 
  selector:
    app: ia-api
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001