artifact_uri: /projets/darija_app_final/mlflow-artifacts/619281650037722963/da19c924b2cc4b66a442ce3b77e3a8a9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '619281650037722963'
lifecycle_stage: active
run_id: da19c924b2cc4b66a442ce3b77e3a8a9
run_name: upset-shrew-235
run_uuid: da19c924b2cc4b66a442ce3b77e3a8a9
source_name: ''
source_type: 4
source_version: ''
start_time: 1753663024921
status: 1
tags: []
user_id: farid
