# Utiliser l'image officielle de Grafana comme base
FROM grafana/grafana:latest

# Copier l'ensemble du dossier de provisioning
# Cela inclut les datasources et les dashboards
COPY provisioning/ /etc/grafana/provisioning/