artifact_uri: /projets/darija_app_final/mlflow-artifacts/619281650037722963/e53db8eb8a584678bd6722d1e7b2d1ea/artifacts
end_time: null
entry_point_name: ''
experiment_id: '619281650037722963'
lifecycle_stage: active
run_id: e53db8eb8a584678bd6722d1e7b2d1ea
run_name: fearless-snipe-859
run_uuid: e53db8eb8a584678bd6722d1e7b2d1ea
source_name: ''
source_type: 4
source_version: ''
start_time: 1753177202517
status: 1
tags: []
user_id: farid
