artifact_uri: /projets/darija_app_final/mlflow-artifacts/619281650037722963/9e32dde321ee4cc6a6c1422cde1baa44/artifacts
deleted_time: 1752938663525
end_time: null
entry_point_name: ''
experiment_id: '619281650037722963'
lifecycle_stage: deleted
run_id: 9e32dde321ee4cc6a6c1422cde1baa44
run_name: mysterious-kite-556
run_uuid: 9e32dde321ee4cc6a6c1422cde1baa44
source_name: ''
source_type: 4
source_version: ''
start_time: 1752786784495
status: 1
tags: []
user_id: farid
