artifact_uri: /projets/darija_app_final/mlflow-artifacts/619281650037722963/3ba0f360af7d47cea6e2753beaab79d9/artifacts
end_time: null
entry_point_name: ''
experiment_id: '619281650037722963'
lifecycle_stage: active
run_id: 3ba0f360af7d47cea6e2753beaab79d9
run_name: bittersweet-lamb-571
run_uuid: 3ba0f360af7d47cea6e2753beaab79d9
source_name: ''
source_type: 4
source_version: ''
start_time: 1753664789045
status: 1
tags: []
user_id: farid
