artifact_uri: /projets/darija_app_final/mlflow-artifacts/619281650037722963/d8b6f55a01ca4b4aac3df3d20d45bbee/artifacts
end_time: null
entry_point_name: ''
experiment_id: '619281650037722963'
lifecycle_stage: active
run_id: d8b6f55a01ca4b4aac3df3d20d45bbee
run_name: likeable-steed-594
run_uuid: d8b6f55a01ca4b4aac3df3d20d45bbee
source_name: ''
source_type: 4
source_version: ''
start_time: 1753135999473
status: 1
tags: []
user_id: farid
