artifact_uri: /projets/darija_app_final/mlflow-artifacts/619281650037722963/18b423d7cdf44a04a0ecd2fc9ee320fd/artifacts
deleted_time: 1752961029185
end_time: null
entry_point_name: ''
experiment_id: '619281650037722963'
lifecycle_stage: deleted
run_id: 18b423d7cdf44a04a0ecd2fc9ee320fd
run_name: big-squirrel-969
run_uuid: 18b423d7cdf44a04a0ecd2fc9ee320fd
source_name: ''
source_type: 4
source_version: ''
start_time: 1752938855445
status: 1
tags: []
user_id: farid
