artifact_uri: /projets/darija_app_final/mlflow-artifacts/619281650037722963/9cfbda1ada284ba89bf6cc2908490643/artifacts
end_time: null
entry_point_name: ''
experiment_id: '619281650037722963'
lifecycle_stage: active
run_id: 9cfbda1ada284ba89bf6cc2908490643
run_name: bright-shrimp-530
run_uuid: 9cfbda1ada284ba89bf6cc2908490643
source_name: ''
source_type: 4
source_version: ''
start_time: 1753541059840
status: 1
tags: []
user_id: farid
