version: '3.8'

services:
  app:
    build:
      context: ../..  
      dockerfile: api/ia_api/Dockerfile
    container_name: darija_api
    env_file:
      - ../../.env
    ports:
      - "8001:8001"
    networks:
      - monitoring_net

  prometheus:
    build:
      context: ./prometheus  
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - monitoring_net
  
  grafana:
    
    build:
      context: ./grafana     
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    
    volumes:
      - grafana-storage:/var/lib/grafana
    
    depends_on:
      - prometheus
    networks:
      - monitoring_net

volumes:
  grafana-storage:

networks:
  monitoring_net:
    driver: bridge

