# api/ia_api/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: ../..  
      dockerfile: api/ia_api/Dockerfile
    container_name: darija_api
    env_file:
      - ../../.env
    ports:
      - "8001:8001"
    networks:
      - monitoring_net

  prometheus:
    build:
      context: ./prometheus  
      dockerfile: Dockerfile
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.local.yml:/etc/prometheus/prometheus.yml
      # On ajoute le fichier de règles au volume
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    environment:
       - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "9090:9090"
    depends_on:
      - app
    networks:
      - monitoring_net
  
  grafana:
    build:
      context: ./grafana     
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/datasources/prometheus.local.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
    depends_on:
      - prometheus
    networks:
      - monitoring_net

  # ===================================================================
  # ===> AJOUTEZ TOUTE CETTE SECTION "alertmanager" <===
  # ===================================================================
  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    volumes:
      # On monte le fichier de configuration créé à l'étape 1
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093" # On expose le port pour pouvoir y accéder depuis notre navigateur
    networks:
      - monitoring_net
  # ===================================================================

volumes:
  grafana-storage:

networks:
  monitoring_net:
    driver: bridge