artifact_uri: /projets/darija_app_final/mlflow-artifacts/619281650037722963/eedfecbdcae24955b7851cc1abc77da7/artifacts
end_time: null
entry_point_name: ''
experiment_id: '619281650037722963'
lifecycle_stage: active
run_id: eedfecbdcae24955b7851cc1abc77da7
run_name: painted-calf-540
run_uuid: eedfecbdcae24955b7851cc1abc77da7
source_name: ''
source_type: 4
source_version: ''
start_time: 1753134993839
status: 1
tags: []
user_id: farid
